# Generated by Django 3.0 on 2019-12-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
