# Generated by Django 3.0 on 2020-01-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardmaker', '0002_deck_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
