# Generated by Django 3.0 on 2020-01-17 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardmaker', '0004_leitnerbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitnerbox',
            name='card',
        ),
        migrations.AddField(
            model_name='deck',
            name='students',
            field=models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leitnerbox',
            name='cards',
            field=models.ManyToManyField(to='cardmaker.Card'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
